# This script was generated by Taurus

from net.grinder.script import Test
from net.grinder.script.Grinder import grinder
from net.grinder.plugin.http import HTTPRequest, HTTPPluginControl, HTTPUtilities
from HTTPClient import NVPair


request = HTTPRequest(url='http://blazedemo.com')
test = Test(1, "BZT Requests")
test.record(request)

defaults = HTTPPluginControl.getConnectionDefaults()
utilities = HTTPPluginControl.getHTTPUtilities()
defaults.setDefaultHeaders([
    NVPair('X-Api-Key', 'my-fresh-token'),
])
defaults.setTimeout(30000)
defaults.setUseCookies(0)

class TestRunner(object):
    def __call__(self):
        request.GET('/', [], [])
        grinder.sleep(1000)
        request.POST('/reserve.php', [], [])
        grinder.sleep(5000)
        request.POST('/payment.php', [], [NVPair('Content-Type', 'application/json')])
        grinder.sleep(1000)
